# Generated by Django 5.1.6 on 2026-02-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicteapproval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosuresection',
            name='s3_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='disclosuresection',
            name='s3_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='institution',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institutiondata',
            name='nba_programs',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
    ]
